<?php

namespace App\Enums;

enum MoneyMovementType: string
{
    case CLIENT_CHARGE = 'CLIENT_CHARGE';
    case CLIENT_REFUND = 'CLIENT_REFUND';
    case OWNER_RELEASE = 'OWNER_RELEASE';
    case PLATFORM_COMMISSION = 'PLATFORM_COMMISSION';
    case PLATFORM_RETENTION = 'PLATFORM_RETENTION';
    case OWNER_WITHDRAWAL = 'OWNER_WITHDRAWAL';
    case OWNER_TRANSFER_SUCCESS = 'OWNER_TRANSFER_SUCCESS';
    case OWNER_TRANSFER_FAILED = 'OWNER_TRANSFER_FAILED';
    case WALLET_RECHARGE = 'WALLET_RECHARGE';
    case CREDIT_ISSUED = 'CREDIT_ISSUED';
    case CREDIT_REDEEMED = 'CREDIT_REDEEMED';
}
